import fs from 'fs';
import path from 'path';
import safeRegex = require('safe-regex2');
import fileSearch = require('./filesearch');
import lessOptions = require('./lessOptions');
import cache = require('./cache');

// The less package ships no type definitions
const less = require('less');

interface WalkOptions {
  ignoreDotFiles?: boolean;
  filter?: (filePath: string) => boolean;
  interval?: number;
  // Unlike filter (which only ever applies to files -- see #73), exclude
  // applies to both files and directories: it's for keeping the walk out of
  // whole subtrees entirely (e.g. node_modules, #72), not for narrowing
  // which files within an otherwise-watched directory count as compilable.
  exclude?: RegExp;
}

interface FilesMap {
  [filePath: string]: fs.Stats;
}

interface WatchCallback {
  (f: string | FilesMap | NodeJS.ErrnoException | null, curr: fs.Stats | null, prev: fs.Stats | null, fileimportlist: Record<string, string[]>): void;
}

interface InitCallback {
  (f: string): void;
}

interface CompileResult {
  outputFilePath: string;
  options: lessOptions.LessRenderOptions;
  cached?: boolean;
}

interface LessWatchCompilerConfig {
  watchFolder?: string;
  outputFolder?: string;
  mainFile?: string;
  sourceMap?: boolean;
  plugins?: string;
  runOnce?: boolean;
  includeHidden?: boolean;
  enableJs?: boolean;
  lessArgs?: string;
  minified?: boolean;
  allowedExtensions?: string[];
  cache?: boolean;
  cachePath?: string;
  exclude?: string;
  // true uses a default "generated file, don't edit" message; a string is
  // custom banner text. Off by default -- prepending anything to existing
  // users' output is a behavior change, so it stays opt-in (issue #82).
  banner?: boolean | string;
}

type WalkCompleteCallback = (err: NodeJS.ErrnoException | null, files: FilesMap | null) => void;

const cwd = process.cwd();
const defaultAllowedExtensions = ['.less'];
// node_modules and .git are near-universally unwanted in the watch tree (large,
// churn heavily, never contain anything this tool should compile) and typing
// them out by hand on every invocation is exactly the friction --exclude (#72)
// was meant to remove, so they're excluded unconditionally rather than only
// when a user thinks to ask for it. Anchored to path-segment boundaries so a
// directory like "my-node_modules-backup" or a file like ".gitignore" isn't
// caught by accident.
const defaultExcludePattern = /(?:^|[\\/])(?:node_modules|\.git)(?:[\\/]|$)/;

const defaultBannerText =
  'This file was generated by less-watch-compiler. Do not edit it directly -- edit the source .less file instead; changes made here will be overwritten.';

// Wraps banner text in a CSS comment, single-line for a one-line message and
// a "/*\n * ...\n */" block for a multi-line one (including multi-line
// custom text supplied via the config file).
function buildBannerComment(banner: boolean | string): string {
  const text = typeof banner === 'string' ? banner : defaultBannerText;
  // A custom banner containing a literal "*/" would otherwise prematurely
  // close the CSS comment, turning the rest of the banner (or whatever
  // followed it) into live CSS. Breaking up the sequence keeps the comment
  // well-formed no matter what text is supplied.
  const lines = text.replace(/\*\//g, '* /').split('\n');
  if (lines.length === 1) return '/* ' + lines[0] + ' */\n';
  return '/*\n' + lines.map((line) => ' * ' + line).join('\n') + '\n */\n';
}

const filelist: string[] = [];
const fileimportlist: Record<string, string[]> = {};

const lessWatchCompilerUtilsModule = {
  config: {} as LessWatchCompilerConfig,

  walk(dir: string, options: WalkOptions, callback: WalkCompleteCallback, initCallback?: InitCallback): void {
    const state = { files: {} as FilesMap, pending: 0 };

    const finalize = (err: NodeJS.ErrnoException | null) => {
      if (state.pending === 0) callback(err, state.files);
    };

    const processDir = (directory: string) => {
      state.pending += 1;
      fs.stat(directory, (err, stat) => {
        if (err) return callback(err as NodeJS.ErrnoException, null);

        state.files[directory] = stat as fs.Stats;
        fs.readdir(directory, (readErr, files) => {
          state.pending -= 1;
          if (readErr) return callback(readErr as NodeJS.ErrnoException, null);

          files.forEach((entry) => {
            const filePath = path.join(directory, entry);
            state.pending += 1;
            fs.stat(filePath, (statErr, st) => {
              let enoent = false;
              if (statErr) {
                if ((statErr as NodeJS.ErrnoException).code !== 'ENOENT') {
                  console.log((statErr as NodeJS.ErrnoException).code);
                  return callback(statErr as NodeJS.ErrnoException, null);
                } else {
                  enoent = true;
                }
              }

              state.pending -= 1;
              if (!enoent && st) {
                // Dotfile/dotfolder skipping and the exclude pattern apply to
                // everything (a directory match keeps the walk from ever
                // descending into it); the extension filter must only apply
                // to files, or directories never recurse
                if (options.ignoreDotFiles && path.basename(filePath)[0] === '.') return void finalize(null);
                if (options.exclude && options.exclude.test(filePath)) return void finalize(null);
                if (!st.isDirectory() && options.filter && options.filter(filePath)) return void finalize(null);

                state.files[filePath] = st as fs.Stats;
                if (st.isDirectory()) {
                  processDir(filePath);
                } else {
                  if (initCallback) initCallback(filePath);
                }
                finalize(null);
              } else {
                finalize(null);
              }
            });
          });

          finalize(null);
        });
      });
    };

    processDir(dir);
  },

  watchTree(root: string, options: WalkOptions | WatchCallback, watchCallback?: WatchCallback, initCallback?: InitCallback): void {
    let opts: WalkOptions;
    let cb: WatchCallback;
    if (typeof options === 'function') {
      cb = options as WatchCallback;
      opts = {};
    } else {
      opts = options as WalkOptions;
      cb = watchCallback as WatchCallback;
    }
    lessWatchCompilerUtilsModule.walk(
      root,
      opts,
      (err: NodeJS.ErrnoException | null, files: FilesMap | null) => {
        if (err) throw err as any;
        if (!files) return;
        const filesMap = files as FilesMap;
        lessWatchCompilerUtilsModule.fileWatcher(root, filesMap, opts, filelist, fileimportlist, cb);
        for (const i in filesMap) {
          lessWatchCompilerUtilsModule.fileWatcher(i, filesMap, opts, filelist, fileimportlist, cb);
        }
        cb(filesMap, null, null, fileimportlist);
      },
      initCallback
    );
  },

  /**
   * Build the standard change handler shared by the CLI and the programmatic
   * API: recompiles every importing ancestor (direct or transitive) when a
   * changed file is someone's @import, otherwise compiles the main file
   * (when set) or the changed file.
   */
  makeWatchHandler(
    mainFilePath: string | undefined,
    notify: {
      onRemove?: (file: string) => void;
      onCompile?: (file: string, result: CompileResult) => void;
      onImportCompile?: (importingFile: string, changedFile: string, result: CompileResult) => void;
    }
  ): WatchCallback {
    return function (f, curr, prev, fileimports) {
      if (typeof f === 'object' && prev === null && curr === null) {
        // Finished walking the tree
        return;
      } else if ((curr as fs.Stats).nlink === 0) {
        // f was removed
        if (notify.onRemove) notify.onRemove(f as string);
      } else if (mainFilePath) {
        // A single main file always wins, regardless of import relationships.
        const compileResult = lessWatchCompilerUtilsModule.compileCSS(mainFilePath);
        if (compileResult && notify.onCompile) notify.onCompile(f as string, compileResult);
      } else {
        // Build a reverse import index once (imported path -> importers)
        // instead of rescanning the whole fileimports map on every BFS step
        // -- with many files and a wide/deep import graph, doing that scan
        // per node makes each change event scale quadratically.
        const importersOf = new Map<string, string[]>();
        for (const i in fileimports) {
          for (const k in fileimports[i]) {
            const importSpec = fileimports[i][k];
            const hasExtension = path.extname(importSpec).length > 1;
            const importFile = hasExtension ? importSpec : importSpec + '.less';
            const normalizedPath = path.normalize(path.dirname(i) + path.sep + importFile);
            const existing = importersOf.get(normalizedPath);
            if (existing) existing.push(i);
            else importersOf.set(normalizedPath, [i]);
          }
        }

        // Find every file that imports the changed file, directly and
        // transitively (e.g. homepage.less -> theme.less -> colors.less:
        // editing colors.less must recompile homepage.less too, not just
        // theme.less -- issue #59), recompiling each ancestor exactly once
        // (a visited set also terminates safely on circular imports).
        const visited = new Set<string>();
        const queue = importersOf.get(f as string) || [];
        while (queue.length > 0) {
          const importer = queue.shift() as string;
          if (visited.has(importer)) continue;
          visited.add(importer);
          const compileResult = lessWatchCompilerUtilsModule.compileCSS(importer);
          if (compileResult && notify.onImportCompile) notify.onImportCompile(importer, f as string, compileResult);
          const grandImporters = importersOf.get(importer);
          if (grandImporters) queue.push(...grandImporters);
        }

        if (visited.size === 0) {
          // Not anyone's import (transitively) -- compile the changed file itself.
          const compileResult = lessWatchCompilerUtilsModule.compileCSS(f as string);
          if (compileResult && notify.onCompile) notify.onCompile(f as string, compileResult);
        }
      }
    };
  },

  compileCSS(file: string, test?: boolean): CompileResult | undefined {
    const outputFilePath = this.resolveOutputPath(file);

    // Skip compiling hidden files unless includeHidden flag is enabled
    if (fileSearch.isHiddenFile(file) && !lessWatchCompilerUtilsModule.config.includeHidden) return;

    const outPath: string = JSON.parse(outputFilePath);
    const config = lessWatchCompilerUtilsModule.config;
    const options = lessOptions.buildRenderOptions({
      inputFilePath: file,
      outputFilePath: outPath,
      enableJs: config.enableJs,
      minified: config.minified,
      sourceMap: config.sourceMap,
      lessArgs: config.lessArgs
    });

    if (!test) {
      // Caching only applies to one-shot compilation (--run-once): that's the
      // scenario the cache targets (CI, restored across runs) and the only
      // one where "was this file actually recompiled" isn't reported back to
      // the caller, so a cache hit can't produce a misleading log line.
      const cacheEnabled = config.cache === true && config.runOnce === true;
      let cachePath: string | undefined;
      let fingerprintInput: Record<string, unknown> | undefined;
      if (cacheEnabled) {
        cachePath = cache.resolvePath(config.cachePath);
        fingerprintInput = {
          enableJs: config.enableJs,
          minified: config.minified,
          sourceMap: config.sourceMap,
          lessArgs: config.lessArgs,
          plugins: config.plugins,
          banner: config.banner
        };
        const mapPath = lessOptions.sourceMapFilePath(options, outPath);
        if (cache.isUpToDate(cachePath, fingerprintInput, file, outPath, mapPath ? [mapPath] : [])) {
          return { outputFilePath, options, cached: true };
        }
      }
      lessWatchCompilerUtilsModule
        .renderLess(file, outPath, options)
        .then(() => {
          if (cacheEnabled && cachePath && fingerprintInput) cache.record(cachePath, fingerprintInput, file, outPath);
        })
        .catch((error: Error & { line?: number; column?: number; filename?: string; extract?: string[] }) => {
          console.log(lessWatchCompilerUtilsModule.formatLessError(error));
          // Under --run-once, many files compile concurrently (none of these
          // promises are awaited by the caller). process.exit(1) would kill
          // the process immediately, mid-write, for any other in-flight
          // renderLess() call -- fs.promises.writeFile() doesn't get to
          // finish, leaving a truncated .css/.map file on disk for a file
          // that would otherwise have compiled successfully (issue #213).
          // Setting exitCode instead lets Node exit on its own once every
          // pending compile actually finishes, preserving the "run-once
          // with a compile error exits non-zero" contract without the race.
          if (config.runOnce) process.exitCode = 1;
        });
    }

    return { outputFilePath, options };
  },

  async renderLess(file: string, outPath: string, options: lessOptions.LessRenderOptions): Promise<void> {
    const renderOptions = { ...options };
    if (lessWatchCompilerUtilsModule.config.plugins) {
      renderOptions.plugins = await lessOptions.loadPlugins(lessWatchCompilerUtilsModule.config.plugins, less, renderOptions);
    }
    const input = await fs.promises.readFile(file, 'utf8');
    const result = await less.render(input, renderOptions);
    let css: string = result.css;
    // When sourceMapFileInline is set, the map is embedded as a data URI in
    // result.css already; a separate .map file would be redundant (and
    // lessc itself never writes one in that mode).
    const mapPath = lessOptions.sourceMapFilePath(options, outPath);

    const banner = lessWatchCompilerUtilsModule.config.banner;
    if (banner) {
      const bannerText = buildBannerComment(banner);
      if (result.map) {
        // Prepending N generated lines ahead of the mapped content shifts
        // every mapping down by N lines; ';' is the mapping-group separator
        // for one generated line, so N empty ones (no segments) at the
        // front reproduce that shift exactly, without needing to touch the
        // rest of the (VLQ-encoded) mappings.
        const bannerLineCount = bannerText.split('\n').length - 1;
        const mapJson = JSON.parse(result.map);
        mapJson.mappings = ';'.repeat(bannerLineCount) + mapJson.mappings;
        const shiftedMap = JSON.stringify(mapJson);
        if (mapPath) {
          result.map = shiftedMap;
        } else {
          // Inline mode: less already appended a data-URI comment carrying
          // the (now-stale) unshifted map to the end of css -- replace it
          // with one carrying the shifted map before the banner moves
          // everything below it down.
          css = css.replace(
            /\/\*# sourceMappingURL=data:application\/json;base64,[\s\S]*?\*\/\s*$/,
            '/*# sourceMappingURL=data:application/json;base64,' + Buffer.from(shiftedMap).toString('base64') + ' */'
          );
        }
      }
      css = bannerText + css;
    }

    await fs.promises.mkdir(path.dirname(path.resolve(outPath)), { recursive: true });
    await fs.promises.writeFile(outPath, css, 'utf8');
    if (result.map && mapPath) {
      await fs.promises.writeFile(mapPath, result.map, 'utf8');
    }
  },

  formatLessError(error: Error & { line?: number; column?: number; filename?: string; extract?: string[]; type?: string }): string {
    if (error.line === undefined && error.filename === undefined) return String(error.stack || error.message || error);
    const kind = error.type ? error.type + 'Error' : 'Error';
    let message = kind + ': ' + error.message;
    if (error.filename) {
      message += ' in ' + error.filename;
      if (error.line !== undefined) message += ' on line ' + error.line + ', column ' + error.column + ':';
    }
    if (error.extract) {
      const firstLine = error.line !== undefined ? error.line - 1 : 0;
      message +=
        '\n' +
        error.extract
          .map((line: string, index: number) => (line !== undefined ? firstLine + index + ' ' + line : undefined))
          .filter((line): line is string => line !== undefined)
          .join('\n');
    }
    return message;
  },

  resolveOutputPath(filePath: string): string {
    const fullPath = path.resolve(filePath);
    const parsedPath = path.parse(fullPath);

    // Only empty when unit testing it seems
    let dirname: string;
    if (lessWatchCompilerUtilsModule.config.watchFolder) {
      const relativePath = path.relative(lessWatchCompilerUtilsModule.config.watchFolder, fullPath);
      dirname = path.dirname(relativePath);
    } else {
      dirname = path.dirname(filePath);
    }
    const filename = parsedPath.name;

    let formatted = path.format({
      dir: dirname || '',
      name: filename,
      ext: (lessWatchCompilerUtilsModule.config.minified ? '.min' : '') + '.css'
    });

    // No matter the path of the main file, the output must always land in the output folder
    formatted = formatted.replace(/^(\.\.[/\\])+/, '');

    const finalFullPath = path.resolve(lessWatchCompilerUtilsModule.config.outputFolder || '', formatted);
    const shortPath = path.relative(cwd, finalFullPath);
    return JSON.stringify(shortPath);
  },

  filterFiles(f: string): boolean {
    const filename = path.basename(f);
    const extension = path.extname(f);
    const allowedExtensions = lessWatchCompilerUtilsModule.config.allowedExtensions || defaultAllowedExtensions;
    if (filename === '' || allowedExtensions.indexOf(extension) === -1) {
      return true;
    } else {
      if (lessWatchCompilerUtilsModule.config.includeHidden) return false;
      return fileSearch.isHiddenFile(filename);
    }
  },

  /**
   * Combine the always-on node_modules/.git exclusion with an optional
   * user-supplied pattern (added, not replacing the default -- a user
   * excluding something unrelated, e.g. --exclude dist, shouldn't silently
   * stop excluding node_modules). Throws if userPattern is not a valid
   * regex, or is rejected by safe-regex2 as having unbounded star height
   * (e.g. `(x+x+)+y`) -- exclude is tested against every path in the tree
   * on every scan, so a catastrophic pattern would hang the watcher.
   * Callers decide how to surface the throw (CLI exits, API throws).
   */
  resolveExcludePattern(userPattern?: string): RegExp {
    if (!userPattern) return defaultExcludePattern;
    const userRegex = new RegExp(userPattern);
    if (!safeRegex(userRegex)) {
      throw new Error('pattern is not safe from catastrophic backtracking (exceeds the allowed repetition/star-height limit)');
    }
    return new RegExp(`(?:${defaultExcludePattern.source})|(?:${userRegex.source})`);
  },

  getDateTime(): string {
    const date = new Date();
    let hour: number | string = date.getHours();
    hour = (hour < 10 ? '0' : '') + hour;
    let min: number | string = date.getMinutes();
    min = (min < 10 ? '0' : '') + min;
    let sec: number | string = date.getSeconds();
    sec = (sec < 10 ? '0' : '') + sec;
    const year = date.getFullYear();
    let month: number | string = date.getMonth() + 1;
    month = (month < 10 ? '0' : '') + month;
    let day: number | string = date.getDate();
    day = (day < 10 ? '0' : '') + day;
    return hour + ':' + min + ':' + sec + ' on ' + day + '/' + month + '/' + year;
  },

  setupWatcher(f: string, files: FilesMap, options: WalkOptions, watchCallback: WatchCallback): void {
    if (lessWatchCompilerUtilsModule.config.runOnce === true) return;
    const watchOptions: fs.WatchFileOptions & { bigint?: false } = {
      bigint: false
    };
    if (options.interval !== undefined) watchOptions.interval = options.interval;
    fs.watchFile(f, watchOptions, (c: fs.Stats, p: fs.Stats) => {
      if (files[f] && !files[f].isDirectory() && c.nlink !== 0 && files[f].mtime.getTime() === c.mtime.getTime()) return;
      if ((c as fs.Stats).nlink === 0) {
        // The file (or directory) appears gone. Some editors save by
        // deleting the original path and recreating it a moment later
        // (rather than an atomic rename), so a single missing poll doesn't
        // necessarily mean a real removal (issue #197: treating it as one
        // used to unwatch the file permanently, silently, right after such
        // a save). fs.watchFile only invokes this callback once on the
        // exists->gone transition -- it will not fire again while the path
        // stays missing -- so a second poll can't be used to confirm this;
        // recheck for real with our own fs.access after one poll interval
        // instead of acting immediately.
        //
        // If the recheck finds the path back, do nothing here: we never
        // unwatched, so fs.watchFile's own next poll independently detects
        // the reappearance (a new mtime) as a normal change below and
        // triggers a recompile through the existing path.
        //
        // Snapshot the last-confirmed-present stat (undefined if the path
        // was never confirmed) so a stale timer can tell it's stale: if a
        // recreate is observed before this timer fires, files[f] is
        // reassigned to a new object below, and this timer's snapshot no
        // longer matches. Without this, a second, unrelated missing poll
        // (e.g. rapid consecutive non-atomic saves) landing just as this
        // timer checks could be mistaken for confirmation of the original
        // poll's removal and unwatch a file that's still actively in use.
        const lastKnownStat = files[f];
        const debounceMs = Math.max(options.interval !== undefined ? options.interval : 0, 300);
        setTimeout(() => {
          if (files[f] !== lastKnownStat) return;
          fs.access(f, fs.constants.F_OK, (accessErr) => {
            if (!accessErr) return;
            if (files[f] !== lastKnownStat) return;
            // A path that never existed also fires this callback once, on
            // its very first poll (e.g. a broken/not-yet-created @import
            // target watched preemptively) -- not a removal, and there's
            // nothing to notify since files[f] was never confirmed present.
            const existed = !!lastKnownStat;
            delete files[f];
            fs.unwatchFile(f);
            if (existed && !(options.ignoreDotFiles && path.basename(f)[0] === '.') && !(options.filter && options.filter(f))) {
              watchCallback(f, c as fs.Stats, p as fs.Stats, fileimportlist);
            }
          });
        }, debounceMs);
        return;
      }
      files[f] = c as fs.Stats;
      if (!files[f].isDirectory()) {
        // Unlike the initial walk() scan (where filter/ignoreDotFiles decide
        // whether a file is even discovered as a watch candidate at all),
        // this per-file change callback must NOT apply those same checks
        // before firing watchCallback: a hidden/filtered file that's only
        // being watched because it's someone's @import target (e.g. the
        // conventional _partial.less naming) still needs its change
        // reported so makeWatchHandler() can find and recompile whatever
        // imports it (issue #59) -- compileCSS() already independently
        // skips producing standalone output for hidden files, which is the
        // correct place for that guard, not here.
        fs.access(f, fs.constants.F_OK, (accessErr) => {
          if (accessErr) {
            console.log('Does not exist : ' + f);
          } else {
            fileimportlist[f] = fileSearch.findLessImportsInFile(f);
            watchCallback(f, c as fs.Stats, p as fs.Stats, fileimportlist);
          }
        });
      } else {
        fs.readdir(f, (err, nfiles) => {
          if (err) return;
          nfiles.forEach((b) => {
            const file = path.join(f, b);
            if (!files[file]) {
              fs.stat(file, (err, stat) => {
                if (err || !stat) return; // raced with a delete between readdir and stat
                if (options.ignoreDotFiles && path.basename(b)[0] === '.') return;
                // Unlike the extension filter below, exclude applies to
                // directories too -- a newly-created excluded directory
                // (e.g. node_modules reappearing after a reinstall) must
                // never start being watched, the same way walk() already
                // keeps the initial scan out of it entirely.
                if (options.exclude && options.exclude.test(file)) return;
                // The extension filter must only apply to files -- a new
                // directory (e.g. one created after startup) never matches
                // an allowed extension, so applying the filter to it too
                // would skip watching it (and everything created inside it
                // afterward) entirely. walk() already gets this right for
                // the initial recursive scan; mirror it here for new
                // directories discovered later by this readdir rescan.
                if (!stat.isDirectory() && options.filter && options.filter(b)) return;
                fs.access(file, fs.constants.F_OK, (accessErr) => {
                  if (accessErr) {
                    console.log('Does not exist : ' + f);
                    return;
                  }
                  files[file] = stat as fs.Stats;
                  if (!stat.isDirectory()) {
                    fileimportlist[file] = fileSearch.findLessImportsInFile(file);
                    watchCallback(file, stat as fs.Stats, null, fileimportlist);
                    lessWatchCompilerUtilsModule.fileWatcher(file, files, options, filelist, fileimportlist, watchCallback);
                    return;
                  }
                  // A new directory: recursively discover anything already
                  // inside it (a directory created together with files
                  // already in it, e.g. via a project scaffold or an editor
                  // batch operation, must not silently miss them -- issue
                  // #73), the same way walk() does for directories found
                  // during the initial scan, then start watching every
                  // discovered file and subdirectory the same way the
                  // initial scan does.
                  lessWatchCompilerUtilsModule.walk(file, options, (walkErr, discovered) => {
                    if (walkErr || !discovered) return;
                    for (const p in discovered) {
                      const s = discovered[p];
                      files[p] = s;
                      if (!s.isDirectory()) {
                        fileimportlist[p] = fileSearch.findLessImportsInFile(p);
                        watchCallback(p, s, null, fileimportlist);
                      }
                      lessWatchCompilerUtilsModule.fileWatcher(p, files, options, filelist, fileimportlist, watchCallback);
                    }
                  });
                });
              });
            }
          });
        });
      }
    });
  },

  fileWatcher(
    f: string,
    files: FilesMap,
    options: WalkOptions,
    filelistArr: string[],
    fileimportlistObj: Record<string, string[]>,
    watchCallback: WatchCallback
  ): void {
    if (filelistArr.indexOf(f) !== -1) return;
    filelistArr[filelistArr.length] = f;

    fileimportlistObj[f] = fileSearch.findLessImportsInFile(f);
    lessWatchCompilerUtilsModule.setupWatcher(f, files, options, watchCallback);
    for (const i in fileimportlistObj[f]) {
      const importSpec = fileimportlistObj[f][i];
      const hasExtension = path.extname(importSpec).length > 1;
      const importFile = hasExtension ? importSpec : importSpec + '.less';
      const importPath = path.normalize(path.dirname(f) + path.sep + importFile);
      // Mirror the directory-walk exclude guard here: an @import target
      // resolving into an excluded path (e.g. --exclude node_modules) must
      // not be watched, or editing it would still trigger the importing
      // parent's recompile even though the subtree is supposed to be kept
      // out entirely (issue #72).
      if (options.exclude && options.exclude.test(importPath)) continue;
      // Only follow @import targets with an allowed extension (.less by
      // default). Less doesn't inline a plain `@import "x.css"` by default
      // (it stays a literal `@import url(...)` reference in the compiled
      // output), so treating such a target as its own watchable entry is
      // both pointless -- recompiling on its change can't affect the
      // importer's output -- and actively wrong, since it would let
      // makeWatchHandler() compile it standalone and produce a spurious
      // .css output for a file that was never meant to be compiled on its
      // own. This must check extension only, NOT hidden-file status: a
      // hidden _partial.less is exactly the kind of target issue #59 needs
      // to keep following.
      const importAllowedExtensions = lessWatchCompilerUtilsModule.config.allowedExtensions || defaultAllowedExtensions;
      if (importAllowedExtensions.indexOf(path.extname(importPath)) === -1) continue;
      // Recurse via fileWatcher(), not a bare setupWatcher() call: the
      // latter registers the watch but never populates fileimportlistObj
      // for the target, relying on a later top-level fileWatcher() call
      // (from watchTree()'s walk-result loop) to do that instead. Depending
      // on directory-walk discovery order, that later call can be pre-empted
      // by fileWatcher()'s own dedup guard before it ever runs, permanently
      // leaving the target's import list empty -- which silently breaks
      // transitive-import recompile detection for anything importing IT
      // (issue #59: homepage.less -> theme.less -> colors.less needs
      // theme.less's own imports recorded for homepage.less to ever be
      // reached when colors.less changes).
      lessWatchCompilerUtilsModule.fileWatcher(importPath, files, options, filelistArr, fileimportlistObj, watchCallback);
      lessWatchCompilerUtilsModule.watchExternalImportDir(importPath, files, options, filelistArr, fileimportlistObj, watchCallback);
    }
  },

  /**
   * An @import target inside watchFolder gets directory-level recreate
   * detection for free: walk() discovers every directory up front, and each
   * one is handed to fileWatcher()/setupWatcher(), whose directory branch
   * notices new files via a readdir rescan. An @import target that resolves
   * outside watchFolder never goes through that walk, so it's watched as a
   * lone file above -- and setupWatcher's removal branch unwatches a deleted
   * file permanently, with nothing watching its directory to notice it come
   * back (issue #209). Mirror the in-root behavior by explicitly watching
   * the external target's containing directory the same way, scoped to just
   * that one directory (not a recursive walk of the external tree).
   */
  watchExternalImportDir(
    importPath: string,
    files: FilesMap,
    options: WalkOptions,
    filelistArr: string[],
    fileimportlistObj: Record<string, string[]>,
    watchCallback: WatchCallback
  ): void {
    const watchFolder = lessWatchCompilerUtilsModule.config.watchFolder;
    if (!watchFolder) return;
    const relative = path.relative(watchFolder, importPath);
    const isExternal = relative.startsWith('..') || path.isAbsolute(relative);
    if (!isExternal) return;

    const importDir = path.dirname(importPath);
    if (filelistArr.indexOf(importDir) !== -1) return;
    let stat: fs.Stats;
    let existingEntries: string[];
    try {
      stat = fs.statSync(importDir);
      existingEntries = fs.readdirSync(importDir);
    } catch {
      // The directory doesn't exist yet; nothing to watch until it does.
      return;
    }
    files[importDir] = stat;
    // Seed every file already in the directory into `files`, mirroring what
    // walk() does up front for directories inside watchFolder. Without this,
    // setupWatcher's directory branch (`if (!files[file])`) would treat each
    // pre-existing sibling as newly added the first time anything else in
    // the directory changes, firing a spurious watchCallback/compile for
    // files that were never touched and aren't anyone's @import.
    for (const entry of existingEntries) {
      const entryPath = path.join(importDir, entry);
      if (files[entryPath]) continue;
      try {
        files[entryPath] = fs.statSync(entryPath);
      } catch {
        // Raced with a delete between readdir and stat; nothing to seed.
      }
    }
    lessWatchCompilerUtilsModule.fileWatcher(importDir, files, options, filelistArr, fileimportlistObj, watchCallback);
  }
};

export = lessWatchCompilerUtilsModule;
